### ISSUE TITLE
Contact OASIS about conformance clauses & Acknowledgements

### ISSUE THREAD

**Issue by sergehuber** [oasis-tcs/cxs-cdp#3]
Can we acknowledge people that are no longer members but were previously ?
Can we get examples of conformance clauses ?

**Comment by chet-ensign** [comment]
Re acknowledgements, yes. Here is an example from the MQTT TC - note that they list people who were active during development of the spec, even though some are no longer in the TC. https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901291

**Comment by chet-ensign** [comment]
For conformance clauses, you can check out the TAB's white paper on drafting conformance clauses at http://docs.oasis-open.org/templates/TCHandbook/ConformanceGuidelines.html

Here is an example in the KMIP Profiles -> http://docs.oasis-open.org/kmip/profiles/v1.4/os/kmip-profiles-v1.4-os.html#_Toc491431613

And here is an example from the TOSCA Simple Profile in YAML -> https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.2/os/TOSCA-Simple-Profile-YAML-v1.2-os.html#_Toc528072999
